use_frameworks!

target 'DataInjector_Example' do
  pod 'DataInjector', :path => '../../'

  target 'DataInjector_Tests' do
    inherit! :search_paths
    pod 'DataInjector', :path => '../../'
  end
end
